Add database
ilyankin/java-filmorate pull request #3
Opened 2022-07-17 17:31 UTC by ilyankin

11 sprint

2022-07-18 07:44 UTC, kukolev requested changes

2022-07-18 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmController.java
> +        return count == null ? filmService.findTopFilmsByLikes(DEFAULT_NUMBER_TOP_FILMS_BY_LIKES) : filmService.findTopFilmsByLikes(count);
Этот код будет работать, но можно проще, через задание значения по умолчанию через аннотацию: `@RequestParam(defaultValue = ... )`

2022-07-18 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/mpa/MpaController.java
> +        if (MpaRating.values().length < id || id < 1) throw new ResourceNotFoundException("MPA", "id", id);
Валидация параметров это часть бизнес-логики. Бизнес-логика должна быть в сервисе. Нужно это доработать.

2022-07-18 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmgenre/FilmGenreDbStorage.java
> +        String selectSqlQuery = "SELECT * FROM " + FILM_GENRES
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-18 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/friendship/FriendshipDbStorage.java
> +        String selectSqlQuery = "SELECT * FROM " + FRIENDSHIPS
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-18 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        String updateSqlQuery = "UPDATE + " + GENRES + " SET " +
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

2022-07-18 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +        String selectSqlQuery = "SELECT * FROM " + FILM_LIKES
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

2022-07-18 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String updateSqlQuery = "UPDATE " + USERS + " SET " +
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-18 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +            put("release_date", releaseDate == null ? null : Date.valueOf(releaseDate));
По моему для release_date лучше использовать LocalDate вместо Date, т.к. не нужна точность больше.

2022-07-18 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "SELECT * FROM " + FILMS + " AS f"
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-18 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/util/DbUtil.java
> +        String selectSqlQuery = "SELECT * FROM " + tableName + " WHERE " + fieldName + " = ?";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-18 09:41 UTC, ilyankin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +            put("release_date", releaseDate == null ? null : Date.valueOf(releaseDate));
Done

2022-07-18 09:41 UTC, ilyankin commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "SELECT * FROM " + FILMS + " AS f"
Done

2022-07-18 09:41 UTC, ilyankin commented on src/main/java/ru/yandex/practicum/filmorate/util/DbUtil.java
> +        String selectSqlQuery = "SELECT * FROM " + tableName + " WHERE " + fieldName + " = ?";
Done

2022-07-18 09:41 UTC, ilyankin commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String updateSqlQuery = "UPDATE " + USERS + " SET " +
Done

2022-07-18 09:41 UTC, ilyankin commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +        String selectSqlQuery = "SELECT * FROM " + FILM_LIKES
Done

2022-07-18 09:41 UTC, ilyankin commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        String updateSqlQuery = "UPDATE + " + GENRES + " SET " +
Done

2022-07-18 09:41 UTC, ilyankin commented on src/main/java/ru/yandex/practicum/filmorate/storage/friendship/FriendshipDbStorage.java
> +        String selectSqlQuery = "SELECT * FROM " + FRIENDSHIPS
Done

2022-07-18 09:41 UTC, ilyankin commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmgenre/FilmGenreDbStorage.java
> +        String selectSqlQuery = "SELECT * FROM " + FILM_GENRES
Done

2022-07-18 17:23 UTC, kukolev requested changes

2022-07-18 17:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmGenre.java
> +    public boolean equals(Object o) {
Чтобы вручную не писать equals и hashCode можно добавить аннотацию `@EqualsAndHashcode`, которая обеспечит создание этих методов на этапе компиляции. Либо добавить аннотацию `@Data`

2022-07-18 17:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Friendship.java
> +    public boolean equals(Object o) {
Чтобы вручную не писать equals и hashCode можно добавить аннотацию `@EqualsAndHashcode`, которая обеспечит создание этих методов на этапе компиляции. Метод toString также заменяется аннотацией `@ToString`. Либо можно добавить аннотацию `@Data`, которая включает все указанные выше аннотации.

2022-07-18 17:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public boolean equals(Object o) {
Чтобы вручную не писать equals и hashCode можно добавить аннотацию `@EqualsAndHashcode`, которая обеспечит создание этих методов на этапе компиляции. Метод toString также заменяется аннотацией `@ToString`. Либо можно добавить аннотацию `@Data`, которая включает все указанные выше аннотации.

2022-07-18 17:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Like.java
> +    public boolean equals(Object o) {
Чтобы вручную не писать equals и hashCode можно добавить аннотацию `@EqualsAndHashcode`, которая обеспечит создание этих методов на этапе компиляции. Метод toString также заменяется аннотацией `@ToString`. Либо можно добавить аннотацию `@Data`, которая включает все указанные выше аннотации.

2022-07-18 17:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmgenre/FilmGenreDbStorage.java
> +    public FilmGenreDbStorage(JdbcTemplate jdbcTemplate, FilmGenreRowMapper filmGenreRowMapper, GenreRowMapper genreRowMapper) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-07-18 17:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +        try (Stream<Like> stream = jdbcTemplate.queryForStream(LIKE_SELECT_SQL_QUERY, likeRowMapper, user_id, film_id)) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-07-18 17:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    private final static String USER_UPDATE_SQL_QUERY = "UPDATE USERS SET email = ?, login = ?, name = ?, birthday = ? WHERE id = ?";
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-07-19 17:20 UTC, kukolev approved these changes

2022-10-10 21:01 UTC, merged